featured_topic_lists_title:
  type: string
  default: "Versatile Showcase"
  description: "Title for showcased lists section"
more_topics_button_text:
  type: string
  default: "More"
  description: "Text displated on More button"
post_button_text:
  type: string
  default: "Post"
  description: "Text displated on Post button"
feed_list:
  placeholder: "Title, List length, Filter, Tag, Category id, Link"
  client: true
  default: ""
  type: list
plugin_outlet:
  type: enum
  default: "above-main-container"
  choices:
    - "above-main-container"
    - "below-site-header"
  description: "Advanced setting for additional customization"
